# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movie' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movie_App
# RXSwift
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'

# Network
  pod 'Alamofire'
  pod 'RxAlamofire'
  pod 'Kingfisher', '~> 4.7.0'
    
# Activity Indicator
  pod 'MBProgressHUD'

# PagerView
  pod 'FSPagerView'

# MGSwipableCell
  pod 'MGSwipeTableCell'
  
  pod 'AppCenter'

end
